kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wcs-psp
rules:
  - apiGroups:
    - extensions
    resources:
    - podsecuritypolicies
    resourceNames:
    - commerce-psp
    verbs:
    - use
