apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: curlalpine
  labels:
    app: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        # Run this image
        image: curlimages/curl:7.72.0
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
