apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-qa-nifi-pvc
  namespace: commerce
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
