cluster:
  nodes: 3
  replicas: 0
usePassword: false
persistence:
  enabled: false
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    selector:
      prometheus: kube-prometheus
redis:
  resources:
    limits:
      cpu: "8"
      memory: 12Gi
    requests:
      cpu: "2"
      memory: 12Gi
  useAOFPersistence: "no"
  configmap: |-
    maxmemory 11000mb
    maxmemory-policy volatile-lru
    slowlog-log-slower-than 10000
    slowlog-max-len 512    
    latency-monitor-threshold 100
    cluster-require-full-coverage no
    save ""
sysctlImage:
  enabled: true
  mountHostSys: true
  command:
    - /bin/sh
    - -c
    - |-
      install_packages procps
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
