usePassword: false
cluster:
  enabled: false
master:
  disableCommands: ""
  persistence:
    enabled: false
  configmap: |-
    appendonly no
    save ""
    maxmemory 1000mb
    maxmemory-policy volatile-lru
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: redis
sysctlImage:
  enabled: true
  mountHostSys: true
  command:
    - /bin/sh
    - -c
    - |-
      install_packages procps
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
