{
 "title": "HCL Cache - Remote",
 "tags": [
  "hcl-cache",
  "hcl"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(hclcache_cache_size_max, namespace)"
    }
   },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(hclcache_cache_size_max{ namespace=\"$namespace\"}, cachespace)"
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(hclcache_cache_size_max{ namespace=~\"$namespace\", cachespace=\"$environment\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(hclcache_cache_size_max{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\"}, pod)"
    }
   },
   {
    "name": "cache",
    "label": "cache",
    "query": {
     "query": "label_values(hclcache_cache_size_max{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\"},name)"
    }
   },
   {
    "name": "redis",
    "query": {
     "query": "label_values(hclcache_cache_remote_node_mapping{ cachespace=\"$environment\" },redis_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients Currently in Outage Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(hclcache_remoteclient_outage{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Remote Clients in Outage Mode",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hclcache_remoteclient_outage{namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\"}) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Caches Currently in Outage Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(hclcache_cache_outage{namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Remote Caches in Outage Mode",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hclcache_cache_outage{namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\"}) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Remote Cache Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Remote Cache Sizes",
   "type": "graph",
   "description": "Cache Manager pod must be enabled",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max( (  hclcache_cache_size_current{ namespace=~\"$namespace\", cachespace=\"$environment\", scope=\"remote\", result!=\"error\", name=~\"$cache\" } > 0 ) * on ( namespace, cachespace, name) group_left( redis_instance ) hclcache_cache_remote_node_mapping{ redis_instance =~ \"$redis\"  }) by ( name, redis_instance )  ",
     "legendFormat": "{{redis_instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Redis Memory",
   "type": "graph",
   "description": "This dashboard only works if Redis is installed\nlocally with metrics enabled",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "{{instance}} - {{pod}} used" },
    { "expr": "max(redis_memory_max_bytes)", "legendFormat": "max" }
   ]
  },
  { "title": "Remote Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Remote Operations per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_puts_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result!=\"error\", name=~\"$cache\"}[2m]))",
     "legendFormat": "put"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result!=\"error\", name=~\"$cache\"}[2m]))",
     "legendFormat": "get"
    },
    {
     "expr": "sum(rate(hclcache_cache_clears_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result!=\"error\", name=~\"$cache\"}[2m]))",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_invalidates_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result!=\"error\", name=~\"$cache\"}[2m]))",
     "legendFormat": "invalidate"
    }
   ]
  },
  {
   "title": "Remote Error Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(hclcache_cache_puts_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result=\"error\", name=~\"$cache\"}[2m]))",
     "legendFormat": "put"
    },
    {
     "expr": "sum(increase(hclcache_cache_gets_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result=\"error\", name=~\"$cache\"}[2m]))",
     "legendFormat": "get"
    },
    {
     "expr": "sum(increase(hclcache_cache_clears_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result=\"error\", name=~\"$cache\"}[2m]))",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(increase(hclcache_cache_invalidates_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result=\"error\", name=~\"$cache\"}[2m]))",
     "legendFormat": "invalidate"
    }
   ]
  },
  {
   "title": "Get Ops per Cache per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\nsum(rate(hclcache_cache_gets_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m])) by (name) > 0\r\r",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Put Ops per Cache per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_puts_duration_seconds_count{ namespace=~\"$namespace\",cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]) ) by (name) ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Clear Ops per Cache per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_clears_duration_seconds_count{ namespace=~\"$namespace\",cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]) ) by (name) ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Invalidate Ops per Cache per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_invalidates_duration_seconds_count{ namespace=~\"$namespace\",cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]) ) by (name) ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Remote Average Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_duration_seconds_sum{ namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m])) / sum(rate(hclcache_cache_gets_duration_seconds_count{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]))",
     "legendFormat": "get"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_duration_seconds_sum{ namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m])) / sum(rate(hclcache_cache_puts_duration_seconds_count{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]))",
     "legendFormat": "put"
    },
    {
     "expr": "sum(rate(hclcache_cache_removes_duration_seconds_sum{ namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m])) / sum(rate(hclcache_cache_puts_duration_seconds_count{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]))",
     "legendFormat": "remove"
    },
    {
     "expr": "sum(rate(hclcache_cache_invalidates_duration_seconds_sum{ namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m])) / sum(rate(hclcache_cache_puts_duration_seconds_count{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]))",
     "legendFormat": "invalidate"
    }
   ]
  },
  {
   "title": "Remote Operations - 95% Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hclcache_cache_gets_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
     "legendFormat": "get"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hclcache_cache_puts_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\"}[5m])) by (le))",
     "legendFormat": "put "
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hclcache_cache_clears_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\"}[5m])) by (le))",
     "legendFormat": "clear"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hclcache_cache_invalidates_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
     "legendFormat": "invalidate"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hclcache_cache_removes_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
     "legendFormat": "remove"
    }
   ]
  },
  {
   "title": "Remote Operations - 99% Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(hclcache_cache_gets_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\"  }[5m])) by (le))",
     "legendFormat": "get"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hclcache_cache_puts_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\"}[5m])) by (le))",
     "legendFormat": "put "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hclcache_cache_clears_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
     "legendFormat": "clear"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hclcache_cache_invalidates_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
     "legendFormat": "invalidate"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hclcache_cache_removes_duration_seconds_bucket{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
     "legendFormat": "remove"
    }
   ]
  },
  { "title": "Hit Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Remote Gets per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result !=\"error\", name=~\"$cache\"}[2m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Remote Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result =\"hit\", name=~\"$cache\"}[2m])) / sum(rate(hclcache_cache_gets_duration_seconds_count{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result !=\"error\", name=~\"$cache\"}[2m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Invalidation Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Dependency Invalidation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_invalidation_messages_total{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", type=\"dependency\", name=~\"$cache\"} [2m] ) ) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cache Clear Invalidation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_invalidation_messages_total{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", type=\"clear\", name=~\"$cache\"}[2m])) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Number of Expired Keys Pending Maintenance",
   "type": "graph",
   "description": "This chart shows the number of keys  that have expired and are pending to be removed by the maintenance processes. Large numbers could indicate maintenance is failing or behind\nCache Manager pod must be enabled\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( hclcache_cache_size_maintenance{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\" } ) by ( name )  > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rate of Expired Keys Removed by Cache",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( rate( hclcache_cache_maintenance_online_keys_total{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result!=\"error\", name=~\"$cache\", scope=\"remote\", type=\"expired\" }[5m]) > 0 ) by  (name) ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Low-Memory Maintenance - Paused PUT Operations by Cache",
   "type": "graph",
   "description": "When the HCL Cache detects that the memory in Redis is almost full, it can temporarily stop PUT operations while Low-Memory maintenance is running ",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( hclcache_cache_remote_put_paused{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", name=~\"$cache\" } ) by (name)  > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rate of Keys Maintained by Type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( rate( hclcache_cache_maintenance_online_keys_total{ namespace=~\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result!=\"error\", name=~\"$cache\", scope=\"remote\" }[5m]  ) ) by  ( type )",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum( rate( hclcache_cache_maintenance_online_keys_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result=\"error\", name=~\"$cache\", scope=\"remote\" }[5m]  ) ) by  ( type )",
     "legendFormat": "{{type}}-error"
    }
   ]
  },
  {
   "title": "Maintenance Average Durations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_maintenance_online_duration_seconds_sum{ namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\", type=\"expired\" }[2m]) ) \r\n / sum(rate(hclcache_cache_maintenance_online_duration_seconds_count{ namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\", type=\"expired\"}[2m]))\r",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(hclcache_cache_maintenance_online_duration_seconds_sum{ namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\", type=\"emergency\" }[2m]) ) \r\n / sum(rate(hclcache_cache_maintenance_online__duration_seconds_count{ namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\", type=\"emergency\"}[2m]))\r",
     "legendFormat": "emergency"
    }
   ]
  }
 ]
}