{
 "title": "REST Performance",
 "tags": [ "hcl" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(request_rest_seconds_count, namespace)"
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(request_rest_seconds_count{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(request_rest_seconds_count{namespace=~\"$namespace\",job=~\"$job\"}, pod)"
    }
   },
   {
    "name": "resource",
    "label": "resource",
    "query": {
     "query": "label_values(request_rest_seconds_count{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\"}, resource)"
    }
   },
   {
    "name": "http_status",
    "label": "http_status",
    "query": {
     "query": "label_values(request_rest_status_total{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\",resource=~\"$resource\"}, http_status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Calls (per second)",
   "type": "graph",
   "description": "Cached requests and errors that happened before the REST call executes (e.g. authentication) are not counted",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\"}[2m]))  by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Status (per second)",
   "type": "graph",
   "description": "Cached requests and errors that trigger before the REST call executes (e.g. authentication) are not counted",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\" }[2m]))  by (http_status)",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "Average Response Times",
   "type": "graph",
   "description": "Cached requests and errors that happened before the REST call executes (e.g. authentication) are not counted",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_rest_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (job) / sum(rate(request_rest_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Calls by Resource (per second)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 17, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\"}[2m]))  by (resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Total Calls by Resource (Increase)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 17, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\"}[2m]))  by (resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Response Times",
     "type": "graph",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m]))  by (resource) / sum(rate(request_rest_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (resource) ",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "95 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(request_rest_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\" }[2m])) by (resource,le))",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "99 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 12, "w": 11, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(request_rest_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\" }[2m])) by (resource,le))",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per Second - Cache Misses",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", cache =\"miss\" }[2m]))  by ( resource) > 0\r",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Requests per Second - Cache Hits",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", cache =\"hit\" }[2m]))  by ( resource) > 0\r",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  }
 ]
}